### ISSUE TITLE
YAlign enhancement

### ISSUE THREAD

**Issue by pazunino** [UweReisewitz/XamarinAndroidEntry#2]
Hi, @UweReisewitz you have done a good job. I'm using this extension in a project that fits very well, only barcode readings and if the label is not readable you can activate the keyboard, excellent.
In my case I have a 5'' screen with only 2 very large ExtendedEntry controls, and the text in the controls is showed at the top.
You can change the XAling but the Entry VerticalTextAlignment property have no effect.
I try to solve searching the cause in the code but the only fix that I could achieve was changing in the Renderer the GravityFlags to show the text vertically centered (e. g. GravityFlags.End | GravityFlags.CenteredVertical instead of only GravityFlags.End).
Perhaps it is possible to add a YAlign, I couldn't, but if you give me a lead I can try again.
Regards and thanks.

**Comment by UweReisewitz** [comment]
Hi,
I'll check into that and get back to you

**Comment by UweReisewitz** [comment]
Hi,
I've added this Feature. Please test and let me know if that's what you wanted.

Plase note that I also updated all nuget packages and corrected some issues found by the Roslyn Code Analyzers.

**Comment by pazunino** [comment]
Hi,
I've tested and added this new feature to my project. It works like expected, It what I wanted.
Thanks for your work, you can close.
Regards.
